site_name: My Docs
site_url: https://tai-src.github.io/how-to-tailor/
theme:
  name: mkdocs
  custom_dir: overrides
# Custom variables
extra:
  github_repo: https://github.com/TAI-src/how-to-tailor
  page_path: how-to-tailor/docs
